cabal install --lib vector
cabal install --lib split
cabal install --lib yesod
cabal install --lib xml-conduit
cabal install --lib hxt
cabal install --lib cassava
cabal install --lib turtle
cabal install --lib text
cabal install --lib graphviz